version: '31'

services:
  coordinator:
    image: "trino-coordinator:${trino_VERSION}"
    ports:
      - "8080:8080"
    container_name: "coordinator"
    command: http://coordinator:8080 coordinator
    networks:
      - trino-network
  worker0:
    image: "trino-worker:${trino_VERSION}"
    container_name: "worker0"
    ports:
      - "8081:8081"
    command: http://coordinator:8080 worker0
    networks:
      - trino-network
#  worker1:
#    image: "trino-worker:${trino_VERSION}"
#    container_name: "worker1"
#    ports:
#      - "8082:8081"
#    command: http://coordinator:8080 worker1
#    networks:
#      - trino-network

networks:
  trino-network:
    driver: bridge
